- name: Process Multiple JSONs
        shell: pwsh
        run: |
          # 1. Načtení Launcherů
          $launchersConfig = Get-Content "data/launchers.json" | ConvertFrom-Json
          $lLines = @()
          foreach ($l in $launchersConfig) {
              $pattern = $l.Companies -join "|"
              foreach ($p in $l.Processes) { $lLines += "    `"$p`" = `"$pattern`"" }
          }
          
          # 2. Načtení Her (spojíme více souborů do jedné hashtable)
          $ubiGames = Get-Content "data/ubisoft.json" | ConvertFrom-Json
          $blizzGames = Get-Content "data/blizzard.json" | ConvertFrom-Json
          
          $gLines = @()
          # Zpracování Ubisoft her
          foreach ($prop in $ubiGames.psobject.Properties) {
              $gLines += "    `"$($prop.Name)`" = `"$($prop.Value)`""
          }
          # Zpracování Blizzard her
          foreach ($prop in $blizzGames.psobject.Properties) {
              $gLines += "    `"$($prop.Name)`" = `"$($prop.Value)`""
          }

          # 3. Sestavení ze šablony
          $template = Get-Content "src/template.ps1" -Raw
          $template = $template.Replace("#INSERT_LAUNCHERS#", ($lLines -join "`r`n"))
          $template = $template.Replace("#INSERT_GAMES#", ($gLines -join "`r`n"))
          
          # Verze a uložení
          $v = Get-Date -Format "yyyy.MM.dd.HHmm"
          $template = $template -replace '0.0.0.0', $v
          $template | Set-Content "LauncherAutoClose.ps1" -Encoding utf8